# Hiển thị nút "Sponsor" trên repo. Bỏ comment / cập nhật nếu bạn có tài khoản tương ứng.
github: [trunghieupham59]
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
# lfx_crowdfunding:
# custom: ['https://example.com/donate']
