import { app, BrowserWindow, ipcMain, shell, nativeTheme, nativeImage } from 'electron'
import path from 'path'
import { registerKeychainHandlers } from './ipc/keychain'
import { registerImageTranslateHandlers } from './ipc/imageTranslate'
import { registerModelsHandlers } from './ipc/models'
import { registerTranscribeHandlers } from './ipc/transcribe'
import { registerTranslateHandlers } from './ipc/translate'
import { registerTtsHandlers } from './ipc/tts'
import { registerChatHandlers } from './ipc/chat'

// Allow audio autoplay after async operations (TTS API calls lose user-gesture context)
app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required')

const isDev = process.env.NODE_ENV === 'development' || !app.isPackaged

// Set app name
app.setName('Lotus')

let mainWindow: BrowserWindow | null = null

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 700,
    minWidth: 780,
    minHeight: 520,
    title: 'Lotus',
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    trafficLightPosition: { x: 16, y: 14 },
    backgroundColor: nativeTheme.shouldUseDarkColors ? '#1a1a2e' : '#ffffff',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
    show: false,
    icon: process.platform === 'win32'
      ? path.join(__dirname, '..', 'build', 'icon.ico')
      : path.join(__dirname, '..', 'build', 'icon.png'),
  })

  if (isDev) {
    mainWindow.loadURL('http://localhost:5173')
    mainWindow.webContents.openDevTools()
  } else {
    mainWindow.loadFile(path.join(__dirname, '..', 'dist', 'index.html'))
  }

  mainWindow.once('ready-to-show', () => {
    mainWindow?.webContents.setZoomLevel(0)
    mainWindow?.show()
  })

  // Disable default Cmd+=/Cmd+- zoom shortcuts
  mainWindow.webContents.on('before-input-event', (event, input) => {
    const isMac = process.platform === 'darwin'
    const ctrlOrCmd = isMac ? input.meta : input.control
    if (ctrlOrCmd && (input.key === '+' || input.key === '=' || input.key === '-' || input.key === '_' || input.key === '0')) {
      event.preventDefault()
    }
  })

  // Open external links in browser
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url)
    return { action: 'deny' }
  })

  mainWindow.on('closed', () => {
    mainWindow = null
  })
}

// ── Open external URL (used by renderer to open System Settings deep links) ──
ipcMain.handle('app:openExternal', async (_event, url: string) => {
  // Allowlist: only permit known safe URL schemes
  const allowed = url.startsWith('https://') || url.startsWith('x-apple.systempreferences:')
  if (!allowed) return
  try {
    await shell.openExternal(url)
  } catch (err) {
    console.error('[openExternal] failed:', err)
  }
})

app.whenReady().then(() => {
  // Set macOS dock icon using base64 (no file path dependency)
  if (process.platform === 'darwin') {
    try {
      // Try base64 first (generated by generate-icons.js)
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const iconBase64: string = require(path.join(__dirname, '..', 'build', 'icon-base64.js'))
      const icon = nativeImage.createFromDataURL(iconBase64)
      if (!icon.isEmpty()) {
        app.dock?.setIcon(icon)
      }
    } catch {
      // Fallback to file path
      const iconPath = path.join(__dirname, '..', 'build', 'icon.png')
      const icon = nativeImage.createFromPath(iconPath)
      if (!icon.isEmpty()) {
        app.dock?.setIcon(icon)
      }
    }
  }

  createWindow()

  // Register IPC handlers
  registerKeychainHandlers(ipcMain)
  registerTranslateHandlers(ipcMain)
  registerModelsHandlers(ipcMain)
  registerTranscribeHandlers(ipcMain)
  registerTtsHandlers(ipcMain)
  registerImageTranslateHandlers(ipcMain)
  registerChatHandlers(ipcMain)

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow()
    }
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

// Security: Prevent new window creation
app.on('web-contents-created', (_event, contents) => {
  contents.on('will-navigate', (event, navigationUrl) => {
    const parsedUrl = new URL(navigationUrl)
    if (parsedUrl.protocol !== 'file:' && navigationUrl !== 'http://localhost:5173/') {
      event.preventDefault()
    }
  })
})
