import { app, BrowserWindow, ipcMain, shell, nativeTheme, nativeImage } from 'electron'
import path from 'path'
import { registerKeychainHandlers } from './ipc/keychain'
import { registerTranslateHandlers } from './ipc/translate'
import { registerModelsHandlers } from './ipc/models'

const isDev = process.env.NODE_ENV === 'development' || !app.isPackaged

// Set app name
app.setName('LOTUS APP')

let mainWindow: BrowserWindow | null = null

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1000,
    height: 680,
    minWidth: 800,
    minHeight: 560,
    title: 'LOTUS APP',
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    trafficLightPosition: { x: 16, y: 16 },
    backgroundColor: nativeTheme.shouldUseDarkColors ? '#1a1a2e' : '#ffffff',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
    show: false,
    icon: process.platform === 'win32'
      ? path.join(__dirname, '..', 'build', 'icon.ico')
      : path.join(__dirname, '..', 'build', 'icon.png'),
  })

  if (isDev) {
    mainWindow.loadURL('http://localhost:5173')
    mainWindow.webContents.openDevTools()
  } else {
    mainWindow.loadFile(path.join(__dirname, '..', 'dist', 'index.html'))
  }

  mainWindow.once('ready-to-show', () => {
    mainWindow?.show()
  })

  // Open external links in browser
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url)
    return { action: 'deny' }
  })

  mainWindow.on('closed', () => {
    mainWindow = null
  })
}

app.whenReady().then(() => {
  // Set macOS dock icon using base64 (no file path dependency)
  if (process.platform === 'darwin') {
    try {
      // Try base64 first (generated by generate-icons.js)
      // eslint-disable-next-line @typescript-eslint/no-var-requires
      const iconBase64: string = require(path.join(__dirname, '..', 'build', 'icon-base64.js'))
      const icon = nativeImage.createFromDataURL(iconBase64)
      if (!icon.isEmpty()) {
        app.dock.setIcon(icon)
      }
    } catch {
      // Fallback to file path
      const iconPath = path.join(__dirname, '..', 'build', 'icon.png')
      const icon = nativeImage.createFromPath(iconPath)
      if (!icon.isEmpty()) {
        app.dock.setIcon(icon)
      }
    }
  }

  createWindow()

  // Register IPC handlers
  registerKeychainHandlers(ipcMain)
  registerTranslateHandlers(ipcMain)
  registerModelsHandlers(ipcMain)

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow()
    }
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

// Security: Prevent new window creation
app.on('web-contents-created', (_event, contents) => {
  contents.on('will-navigate', (event, navigationUrl) => {
    const parsedUrl = new URL(navigationUrl)
    if (parsedUrl.protocol !== 'file:' && navigationUrl !== 'http://localhost:5173/') {
      event.preventDefault()
    }
  })
})
